services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=banking_app/app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python -m flask run --host=0.0.0.0
