version: "3.8"
services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/usr/local/etc/haproxy/certs:ro
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=banking_app/app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
