name: Python Linting and Testing on PR

on:
  pull_request:
    types: 
      - opened
  push:
    branches: [ main ]
    paths-ignore:
      - './banking_app'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.2'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy autopep8

    - name: Run flake8
      run: flake8

    - name: Run autopep8
      run: |
        autopep8 --diff --exit-code --recursive .
    - name: Run mypy
      run: |
        mypy --strict --allow-untyped-decorators --ignore-missing-imports logic
        mypy --strict --allow-untyped-decorators --ignore-missing-imports database

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:${GITHUB_WORKSPACE}/" >> $GITHUB_ENV

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  pytest pytest-cov

    - name: Run tests
      run: |
        pytest --verbose logic/main.py
        pytest --verbose database/models.py
        
    - name: Run pytest with coverage
      run: |
        pytest --cov=tests/ --cov-report=term-missing
        pytest --cov=tests/ --cov-report=term-missing
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov

  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codespell
    - name: Check spelling
      run: codespell
